version: '3'
services:
  mysql:
    image: mysql
    container_name: library-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:
